/* eslint-disable @next/next/no-img-element */
/* eslint-disable @next/next/no-sync-scripts */
import Document, {Html, Head, Main, NextScript} from "next/document";
import Link from "next/link";

class MyDocument extends Document{
    render(){
        return(
            <Html lang="en">
                 <Head>
                    
                    <meta name="description" content="Generated by create next app" />
                    
                    <link rel="icon"  sizes="180x180" href="/logoC.png" />
                    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" />
                    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
                    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
                    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
                    <script src={`https://www.paypal.com/sdk/js?client-id=${process.env.PAYPAL_CLIENT_ID}`}></script>
                 </Head>
                 <body>
                     <Main>

                     </Main>
                     <NextScript>

                     </NextScript>
                 <footer>
                 <div style={{marginTop: "50px", marginLeft: '20px'}}>
        <ul>
            <li>
                <Link href="/contact">
                    <a>CONTACT US</a>
                </Link>
            </li>
            <li>
               <Link href='#'>
                    <a>FAQS</a>
                </Link>
            </li>
            <li>
                <Link href='#'>
                    <a>SHIPPING &#38; RETURN</a>
                </Link>
            </li>
            <li>
                <Link href='#'>
                    <a>PAYMENT METHODS</a>
                </Link>
            </li>
        <br />
            <li>
                <Link href='#'>
                    <a>INSTAGRAM</a>
                </Link>
            </li>
            <li>
                <Link href='#'>
                    <a>LOOK BOOK</a>
                </Link>
            </li>
        </ul>
       
       
         </div>
                 </footer>
                 </body>
            </Html>
        )
    }
}
export default MyDocument